run:
  modules-download-mode: readonly
  go: '1.21.3'
  timeout: 5m
  skip-dirs:
    - ./internal
    - ./querybuilder

linters:
  disable-all: true
  enable:
    - gofmt
    - goimports
    - goprintffuncname
    - typecheck
    - unconvert
    - unused
    - whitespace