name: Integration Test

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  lint:
    name: Run integration test
    runs-on: ubuntu-latest
    env:
      DAGGER_CLOUD_TOKEN: ${{ secrets.DAGGER_CLOUD_TOKEN }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Dagger Zenith
        run: |
          git clone https://github.com/dagger/dagger
          cd ./dagger
          ./hack/dev
          sudo mv ./bin/dagger /usr/local/bin

      - name: Check Zenith Install
        run: |
          dagger version

      - name: Run lint
        env:
          _EXPERIMENTAL_DAGGER_RUNNER_HOST: "docker-container://dagger-engine:dev"
        run: |
          cd ci
          sudo dagger mod sync
          sudo dagger call integration-test run