name: Lint

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  lint:
    name: Lint project
    runs-on: ubuntu-latest
    env:
      DAGGER_CLOUD_TOKEN: ${{ secrets.DAGGER_CLOUD_TOKEN }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Dagger Zenith
        run: |
          git clone https://github.com/dagger/dagger dagger-zenith
          cd ./dagger-zenith
          ./hack/dev
          sudo mv ./bin/dagger /usr/local/bin

      - name: Check Zenith Install
        run: |
          dagger version

      - name: Sync modules
        env:
          _EXPERIMENTAL_DAGGER_RUNNER_HOST: "docker-container://dagger-engine:dev"
        run: |
          for f in *; do if [ -d $f ]; then sudo dagger mod sync --workdir $f;  fi;  done

      - name: Run lint
        env:
          _EXPERIMENTAL_DAGGER_RUNNER_HOST: "docker-container://dagger-engine:dev"
        run: |
          cd ci
          sudo dagger call lint